be15-4th-project/be15-4th-DAO-NBTI-front

be15-4th-dao-nbti-fe/package-lock.json
be15-4th-dao-nbti-fe/package.json
be15-4th-dao-nbti-fe/src/.env
be15-4th-dao-nbti-fe/src/api/axios.js
be15-4th-dao-nbti-fe/src/components/layout/Header.vue
be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue
be15-4th-dao-nbti-fe/src/features/main/router.js
be15-4th-dao-nbti-fe/src/features/main/views/MainView.vue
be15-4th-dao-nbti-fe/src/features/user/components/component.vue
be15-4th-dao-nbti-fe/src/features/user/views/login.vue
be15-4th-dao-nbti-fe/src/main.js
be15-4th-dao-nbti-fe/src/router/index.js
be15-4th-dao-nbti-fe/src/stores/auth.js

[init] 초기 작업

---

be15-4th-dao-nbti-fe/src/components/layout/Header.vue
be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue

📌 개요
헤어 컴포넌트 생성
🔨 주요 변경 사항
헤어 컴포넌트 생성
✅ 리뷰 요청 사항
헤어 컴포넌트 생성
⭐ 관련 이슈
#

[init] 헤더 컴포넌트 생성

---

be15-4th-dao-nbti-fe/src/components/common/BigModal.vue
be15-4th-dao-nbti-fe/src/components/common/SmallModal.vue

closes #
---
📌 개요
Modal 수정
🔨 주요 변경 사항
- Modal 에서 취소와 확인 메세지 위치 수정
- message 대신에 slot으로 대체해서 끼워 넣기
✅ 리뷰 요청 사항
추가로 필요한 변경사항
⭐ 관련 이슈
#

refactor : 모달 내용 위치 수정 및 slot 추가

---

be15-4th-dao-nbti-fe/env
be15-4th-dao-nbti-fe/src/features/mypage/api.js
be15-4th-dao-nbti-fe/src/features/mypage/views/StudyListView.vue

closes #000
---
📌 개요
🔨 주요 변경 사항
- StudyListView.vue
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

feat : 학습 내역 목록 조회 api 연동

---

be15-4th-dao-nbti-fe/src/features/test/views/TestView.vue

closes #000
---
📌 개요
TestView가 없어 발생하는 오류 해결을 위한 임시 뷰
🔨 주요 변경 사항
- `TestView` 넣기 (임시)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

fix : TestView가 없어 발생하는 오류 해결을 위한 임시 뷰

---

be15-4th-dao-nbti-fe/src/features/admin/router.js
be15-4th-dao-nbti-fe/src/features/admin/views/ProblemCreateView.vue
be15-4th-dao-nbti-fe/src/features/admin/views/ProblemSearchView.vue

closes #12 
---
📌 개요
문제 등록 페이지 구현
🔨 주요 변경 사항
- 문제 등록 페이지 구현 (파일 업로드 로직 수정 필요)
이전 PR과 마찬가지로 모든 페이지 완성 후에 로직 건드려 보겠습니다.
- 문제 목록 조회 페이지에 문제 등록 버튼 추가 (refactor #10)
✅ 리뷰 요청 사항
⭐ 관련 이슈
#12

feat: 문제 등록 페이지 구현

---

be15-4th-dao-nbti-fe/src/router/index.js

📌 개요
index.js - testRoutes 누락 해결

fix: index.js - testRoutes 누락 해결

---

be15-4th-dao-nbti-fe/src/features/admin/api.js
be15-4th-dao-nbti-fe/src/features/admin/components/PagingBar.vue
be15-4th-dao-nbti-fe/src/features/admin/views/UserListView.vue
be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue

closes #26 
---
📌 개요
사용자 목록을 조회할 수 있는 관리자 페이지이다.
🔨 주요 변경 사항
✅ 리뷰 요청 사항
페이지 정상 동작
⭐ 관련 이슈
#

feat: 회원 목록 조회 페이지 구현

---

be15-4th-dao-nbti-fe/src/features/admin/api.js
be15-4th-dao-nbti-fe/src/features/admin/router.js
be15-4th-dao-nbti-fe/src/features/admin/views/TestListView.vue

closes #27 
---
📌 개요
검사 결과 조회 페이지 구현
🔨 주요 변경 사항
검사 결과 조회 페이지 구현
✅ 리뷰 요청 사항
페이지 정상 동작 확인
⭐ 관련 이슈
#

feat: 검사 결과 조회 페이지 구현

---

be15-4th-dao-nbti-fe/src/features/admin/api.js
be15-4th-dao-nbti-fe/src/features/admin/router.js
be15-4th-dao-nbti-fe/src/features/admin/views/AdminTestDetailView.vue
be15-4th-dao-nbti-fe/src/features/user/api.js
be15-4th-dao-nbti-fe/src/features/user/components/FindPasswordForm.vue
be15-4th-dao-nbti-fe/src/features/user/components/LoginForm.vue
be15-4th-dao-nbti-fe/src/features/user/components/ResetPasswordForm.vue
be15-4th-dao-nbti-fe/src/features/user/router.js
be15-4th-dao-nbti-fe/src/features/user/views/FindPaswordView.vue
be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue
be15-4th-dao-nbti-fe/src/features/user/views/ResetPasswordView.vue

closes #28
closes #22
---
📌 개요
검사 결과 상세 페이지 구현
비밀번호 변경 페이지 구현
🔨 주요 변경 사항
검사 결과 상세 페이지 구현
비밀번호 변경 페이지 구현
✅ 리뷰 요청 사항
페이지 정상 동작 확인
비밀번호 변경 페이지 구현
⭐ 관련 이슈
#28
#22

feat: 검사 결과 상세 페이지 및 비밀번호 변경 페이지 구현

---

be15-4th-dao-nbti-fe/src/features/test/api.js
be15-4th-dao-nbti-fe/src/features/test/router.js
be15-4th-dao-nbti-fe/src/features/test/views/TestView.vue

closes #18
---
📌 개요
검사 진행 기능 페이지 구현 및 api 연동
🔨 주요 변경 사항
- `test/api.js` 문제 채점하는 api 연동
- `router.js` TestView의 이름 변경
- `TestView ` 페이지 수정 및 연동된 api 사용
✅ 리뷰 요청 사항
⭐ 관련 이슈
#18

feat : 검사 진행 기능 페이지 구현 및 api 연동

---

be15-4th-dao-nbti-fe/src/components/layout/Header.vue
be15-4th-dao-nbti-fe/src/features/mypage/api.js
be15-4th-dao-nbti-fe/src/features/mypage/views/UserInfoView.vue

closes #24 
---
📌 개요
회원 탈퇴 기능 구현 및 헤더 밑줄 제거
🔨 주요 변경 사항
회원 탈퇴 기능 구현
헤더의 a태그 text-decoration : none 적용
✅ 리뷰 요청 사항
⭐ 관련 이슈
#24

feat: 회원 탈퇴 기능 구현

---

be15-4th-dao-nbti-fe/src/features/test/api.js
be15-4th-dao-nbti-fe/src/features/test/views/TestResultView.vue

closes #000
---
📌 개요
검사 결과 페이지에서 잘못된 경로 수정
🔨 주요 변경 사항
- `api.js`에서 경로에 testResultId 추가
- `TestResultView` 수정하기 
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

fix : 잘못된 api 경로 수정

---

be15-4th-dao-nbti-fe/src/features/study/views/StudyView.vue

📌 개요
작업 기억 카테고리 문제들에 대한 요구사항 반영(숫자 한 개씩 화면에 출력)
🔨 주요 변경 사항
- 17번 카테고리인 경우 주어진 정답을 통해 역으로 문제를 생성
- 17번 카테고리(작업 기억)에 대해서 시작 버튼을 설정하여 준비되면 화면에 숫자 1개씩 출력하도록 구현
- 17번 카테고리에 한하여 이미지 클릭을 통한 확대 모달을 비활성화

refactor: 작업 기억 카테고리 문제들에 대한 요구사항 반영(숫자 한 개씩 화면에 출력)

---

be15-4th-dao-nbti-fe/src/features/admin/views/ObjectionDetailsView.vue
be15-4th-dao-nbti-fe/src/features/admin/views/ObjectionSearchView.vue

closes null
---
📌 개요
- 관리자 이의 제기 조회 페이지에 이의 제기 ID 추가
🔨 주요 변경 사항
- 이의 제기 목록 조회
- 이의 제기 상세 조회
- 회원 아이디 -> 회원 ID로 통일
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

refactor: 관리자 이의 제기 조회 페이지 수정

---

be15-4th-dao-nbti-fe/index.html

closes #000
---
📌 개요
브라우저 탭의 홈페이지 이름 수정
🔨 주요 변경 사항
- 브라우저 탭의 이름을 Vite App 에서 NBTI로 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

refactor : 브라우저 탭의 홈페이지 이름 수정

---

be15-4th-dao-nbti-fe/src/features/main/components/StudyCategoryListFrame.vue

📌 개요
학습 시작 전 안내 모달 닫기 버튼 동작 오류 수정

fix: 학습 시작 전 안내 모달 닫기 버튼 동작 오류 수정

---

be15-4th-dao-nbti-fe/src/components/layout/Footer.vue
be15-4th-dao-nbti-fe/src/components/layout/LayoutDefault.vue

closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

[init] footer 생성

---

be15-4th-dao-nbti-fe/src/features/user/components/LoginForm.vue
be15-4th-dao-nbti-fe/src/features/user/views/LoginView.vue

closes #000
---
📌 개요
로그인 성공 시 모달창 뜨지 않게 수정
🔨 주요 변경 사항
- `LoginForm` 엔터키 누르는 경우 로그인 될 수 있게 수정
- `LoginView` 로그인 성공 시 모달 창 뜨지 않게 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

refactor : 로그인 성공 시 모달창 뜨지 않게 수정

---

be15-4th-dao-nbti-fe/src/features/admin/views/ProblemCreateView.vue

📌 개요
- 등록된 문제 번호를 알 수 없었던 문제 수정
🔨 주요 변경 사항
- 문제 등록 후 해당 문제 상세 페이지로 이동하도록 수정
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

refactor: 문제 등록 페이지 수정

---

be15-4th-dao-nbti-fe/src/features/mypage/views/ObjectionListView.vue

closes #000
---
📌 개요
🔨 주요 변경 사항
✅ 리뷰 요청 사항
⭐ 관련 이슈
#

refactor : 이의제기 상세조회의 관리자  처리 사유 확인

---

be15-4th-dao-nbti-fe/src/features/admin/router.js
be15-4th-dao-nbti-fe/src/router/index.js

closes #000
---
📌 개요
- 회원이 관리자 페이지에 접근 가능한 문제 수정
🔨 주요 변경 사항
- 주소 창에 "/admin"을 작성하면 관리자 페이지에 접근되는 문제 수정
- 전역 라우터 설정
✅ 리뷰 요청 사항
- 설정 적절한지
⭐ 관련 이슈

[fix] 회원이 관리자 페이지에 접근 가능한 문제 수정

---

be15-4th-dao-nbti-fe/src/api/axios.js

fix: axios 기본 경로 수정

---

be15-4th-dao-nbti-fe/index.html

앱 로드 시점 이전에 window.env에 axios 기본 경로 변수 등록하기

fix: 앱 로드 시점 이전에 window.env에 axios 기본 경로 변수 등록하기
